version: 2.1

executors:
  docker-cimg-base:
    docker:
      - image: cimg/base:stable

jobs:
  build-and-publish:
    executor: docker-cimg-base
    parameters:
      container-tag:
        type: string
        default: base
    environment:
      CONTAINER_TAG: << parameters.container-tag >>
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Create a new builder instance
          command: docker buildx create --use
      - run:
          name: Build and publish
          command: make CONTAINER_TAG=${CONTAINER_TAG} container-buildx-push

workflows:
  build-deploy:
    jobs:
      - build-and-publish:
          context:
            - dockerhub
            - quay-og
            - github-registry
          matrix:
            parameters:
              container-tag:
                - base
                - sql
                - ffmpeg
                - ffmpeg-sql
                - full
                - full-sql
          filters:
            tags:
              only: /.*/
